### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by alexmines** [AlexSpagnuolo/portfolio#1]
| 3 | 3 | 3 | 3 | 3 |
| **Creativeness** |  Very unique, and reflects you as a person and designer very well |
| **Effectiveness** | Easy to navigate| Straight to the point |
| **Quality** | Very high quality | Visually pleasing |
| **Effort** | A lot of effort put into the coding and visual look |
| **Code quality** | Goes beyond what we learnt in class for the code |

**Comment by alexspgn** [comment]
Thanks Alex!
