### ISSUE TITLE
Browser Testing - Opera at small sizes

### ISSUE THREAD

**Issue by ksheedy** [AlexSpagnuolo/portfolio#14]
Hey Alex - when using Opera at small screen sizes (320px), the header/nav of your website breaks into two lines. Everything else looks great!
![screenshot 2018-12-14 08 51 33](https://user-images.githubusercontent.com/22224979/50006989-77c20900-ff7d-11e8-9eb3-cef10d5d59cb.png)

**Comment by alexspgn** [comment]
Thanks, Katie.
